#!/usr/bin/env bash
# ==============================================================================
# install-antigravity.sh
# 
# Installer & In-Place Updater utility for Antigravity 2.0 on Fedora Linux
# (KDE Plasma & Freedesktop compliant).
# 
# Generated by: Antigravity AI Assistant (Google DeepMind)
# Model: Gemini 3.8 Flash
# Date: October 2026
# SPDX-License-Identifier: MIT
# License: MIT (see LICENSE)
# ==============================================================================

set -euo pipefail

# Text formatting
BOLD="\033[1m"
GREEN="\033[32m"
BLUE="\033[34m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

log_info()  { echo -e "${BLUE}${BOLD}[INFO]${RESET} $*"; }
log_ok()    { echo -e "${GREEN}${BOLD}[OK]${RESET} $*"; }
log_warn()  { echo -e "${YELLOW}${BOLD}[WARN]${RESET} $*"; }
log_error() { echo -e "${RED}${BOLD}[ERROR]${RESET} $*" >&2; }

# Defaults
DEFAULT_DEST_DIR="${HOME}/.local/share/antigravity"
DEFAULT_BIN_DIR="${HOME}/.local/bin"
APP_NAME="Antigravity"
DESKTOP_ID="antigravity"

DEST_DIR="${DEFAULT_DEST_DIR}"
BIN_DIR="${DEFAULT_BIN_DIR}"
CUSTOM_ICON=""
ARCHIVE_PATH=""
DO_UNINSTALL=false

show_help() {
    echo -e "${BOLD}Antigravity 2.0 Installer for Fedora Linux (KDE Plasma)${RESET}

Usage:
  $(basename "$0") [OPTIONS] [PATH_TO_TAR_GZ]

Options:
  -d, --dest <DIR>       Destination directory for application files
                         (default: ${DEFAULT_DEST_DIR})
  -b, --bin-dir <DIR>    Directory for the terminal launcher command
                         (default: ${DEFAULT_BIN_DIR})
  -i, --icon <PATH>      Custom application icon (.png or .svg).
                         If omitted, extracts the official 512x512 icon
                         embedded inside resources/app.asar.
  -u, --uninstall        Remove Antigravity installation, desktop entry,
                         icons, and terminal command.
  -h, --help             Show this help message and exit.

Examples:
  # Install using an explicit tarball path:
  $(basename "$0") ~/Downloads/Antigravity.tar.gz

  # Install using automatic detection from ~/Downloads or current dir:
  $(basename "$0")

  # Install with a custom icon:
  $(basename "$0") --icon ~/Pictures/my-icon.png ~/Downloads/Antigravity.tar.gz

  # Uninstall:
  $(basename "$0") --uninstall"
}

# Parse options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_help
            exit 0
            ;;
        -d|--dest)
            DEST_DIR="$(realpath -m "$2")"
            shift 2
            ;;
        -b|--bin-dir)
            BIN_DIR="$(realpath -m "$2")"
            shift 2
            ;;
        -i|--icon)
            CUSTOM_ICON="$(realpath "$2")"
            shift 2
            ;;
        -u|--uninstall)
            DO_UNINSTALL=true
            shift
            ;;
        -*)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            if [[ -z "${ARCHIVE_PATH}" ]]; then
                ARCHIVE_PATH="$(realpath "$1")"
            else
                log_error "Unexpected argument: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

# ------------------------------------------------------------------------------
# Refresh desktop and icon databases
# ------------------------------------------------------------------------------
refresh_system_caches() {
    log_info "Updating system icon and desktop entry caches..."

    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true
    fi

    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "${HOME}/.local/share/applications" 2>/dev/null || true
    fi

    # KDE Plasma Sycoca cache refresh (Plasma 6 / Plasma 5)
    if command -v kbuildsycoca6 >/dev/null 2>&1; then
        kbuildsycoca6 2>/dev/null || true
    elif command -v kbuildsycoca5 >/dev/null 2>&1; then
        kbuildsycoca5 2>/dev/null || true
    fi
}

# ------------------------------------------------------------------------------
# Uninstall Routine
# ------------------------------------------------------------------------------
if [[ "${DO_UNINSTALL}" == "true" ]]; then
    log_info "Starting uninstallation of Antigravity..."

    # Remove application directory
    if [[ -d "${DEST_DIR}" ]]; then
        rm -rf "${DEST_DIR}"
        log_ok "Removed application directory: ${DEST_DIR}"
    fi

    # Remove terminal binary
    if [[ -f "${BIN_DIR}/${DESKTOP_ID}" || -L "${BIN_DIR}/${DESKTOP_ID}" ]]; then
        rm -f "${BIN_DIR}/${DESKTOP_ID}"
        log_ok "Removed terminal launcher: ${BIN_DIR}/${DESKTOP_ID}"
    fi

    # Remove desktop entry
    DESKTOP_FILE="${HOME}/.local/share/applications/${DESKTOP_ID}.desktop"
    if [[ -f "${DESKTOP_FILE}" ]]; then
        rm -f "${DESKTOP_FILE}"
        log_ok "Removed desktop entry: ${DESKTOP_FILE}"
    fi

    # Remove installed icons
    ICON_BASE="${HOME}/.local/share/icons/hicolor"
    for size in 16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512 scalable; do
        for ext in png svg; do
            target="${ICON_BASE}/${size}/apps/${DESKTOP_ID}.${ext}"
            if [[ -f "${target}" ]]; then
                rm -f "${target}"
            fi
        done
    done
    rm -f "${HOME}/.local/share/pixmaps/${DESKTOP_ID}.png" 2>/dev/null || true
    log_ok "Removed desktop icons"

    refresh_system_caches
    log_ok "Antigravity uninstalled successfully."
    exit 0
fi

# ------------------------------------------------------------------------------
# Version detection helper
# ------------------------------------------------------------------------------
get_app_version() {
    local asar_file="$1"
    if [[ ! -f "${asar_file}" ]]; then
        echo "unknown"
        return
    fi
    python3 - "${asar_file}" 2>/dev/null << 'EOF' || echo "unknown"
import sys, struct, json
try:
    with open(sys.argv[1], "rb") as f:
        magic, header_len = struct.unpack("<II", f.read(8))
        f.seek(12)
        json_len = struct.unpack("<I", f.read(4))[0]
        header = json.loads(f.read(json_len).decode("utf-8"))
        pkg = header["files"]["package.json"]
        offset = int(pkg["offset"])
        size = int(pkg["size"])
        f.seek(8 + header_len + offset)
        pkg_data = json.loads(f.read(size).decode("utf-8"))
        print(pkg_data.get("version", "unknown"))
except Exception:
    print("unknown")
EOF
}

# ------------------------------------------------------------------------------
# Archive resolution
# ------------------------------------------------------------------------------
if [[ -z "${ARCHIVE_PATH}" ]]; then
    log_info "No tarball path provided. Checking current directory and ~/Downloads..."
    # Find archives and sort by modification timestamp (newest first)
    NEWEST_ARCHIVE="$(find . "${HOME}/Downloads" -maxdepth 1 \( -iname "*antigravity*.tar.gz" -o -iname "*antigravity*.tgz" \) -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n 1 | cut -d' ' -f2-)"

    if [[ -n "${NEWEST_ARCHIVE}" && -f "${NEWEST_ARCHIVE}" ]]; then
        ARCHIVE_PATH="${NEWEST_ARCHIVE}"
        log_info "Auto-detected most recently downloaded build: ${ARCHIVE_PATH}"
    else
        log_error "Could not find an Antigravity .tar.gz archive."
        log_error "Please specify the path: $(basename "$0") /path/to/Antigravity.tar.gz"
        exit 1
    fi
fi

if [[ ! -f "${ARCHIVE_PATH}" ]]; then
    log_error "Archive file not found: ${ARCHIVE_PATH}"
    exit 1
fi

# Check if application is currently running
if pgrep -x "antigravity" >/dev/null 2>&1; then
    log_warn "Antigravity appears to be currently running."
    log_warn "If you experience issues, please close Antigravity before updating."
fi

# Detect currently installed version if updating
OLD_VERSION="none"
if [[ -f "${DEST_DIR}/resources/app.asar" ]]; then
    OLD_VERSION="$(get_app_version "${DEST_DIR}/resources/app.asar")"
fi

# Verify it is a valid gzip archive
if ! gzip -t "${ARCHIVE_PATH}" 2>/dev/null; then
    log_error "The specified file is not a valid gzip file: ${ARCHIVE_PATH}"
    exit 1
fi

# Check required system utilities
for tool in tar python3; do
    if ! command -v "${tool}" >/dev/null 2>&1; then
        log_error "Required utility '${tool}' is not installed."
        exit 1
    fi
done

# ------------------------------------------------------------------------------
# Extraction to destination directory
# ------------------------------------------------------------------------------
log_info "Preparing installation destination: ${DEST_DIR}"
TEMP_EXTRACT_DIR="$(mktemp -d -t antigravity-install-XXXXXX)"

cleanup() {
    rm -rf "${TEMP_EXTRACT_DIR}"
}
trap cleanup EXIT

log_info "Extracting archive: ${ARCHIVE_PATH}..."
tar -zxvf "${ARCHIVE_PATH}" -C "${TEMP_EXTRACT_DIR}" >/dev/null

# Determine if archive extracted into a single root folder (e.g. Antigravity-x64)
EXTRACTED_ITEMS=("${TEMP_EXTRACT_DIR}"/*)
SOURCE_ROOT="${TEMP_EXTRACT_DIR}"

if [[ ${#EXTRACTED_ITEMS[@]} -eq 1 && -d "${EXTRACTED_ITEMS[0]}" ]]; then
    SOURCE_ROOT="${EXTRACTED_ITEMS[0]}"
fi

if [[ ! -f "${SOURCE_ROOT}/antigravity" ]]; then
    # Try searching one level deeper if structure differs
    FOUND_BIN="$(find "${TEMP_EXTRACT_DIR}" -maxdepth 3 -type f -name "antigravity" 2>/dev/null | head -n 1)"
    if [[ -n "${FOUND_BIN}" ]]; then
        SOURCE_ROOT="$(dirname "${FOUND_BIN}")"
    else
        log_error "Could not find 'antigravity' executable inside the extracted archive."
        exit 1
    fi
fi

# Install / replace target directory
mkdir -p "$(dirname "${DEST_DIR}")"
if [[ -d "${DEST_DIR}" ]]; then
    log_info "Replacing existing directory at ${DEST_DIR}..."
    rm -rf "${DEST_DIR}"
fi

mkdir -p "${DEST_DIR}"
cp -a "${SOURCE_ROOT}/." "${DEST_DIR}/"
chmod +x "${DEST_DIR}/antigravity"
if [[ -f "${DEST_DIR}/chrome-sandbox" ]]; then
    chmod 4755 "${DEST_DIR}/chrome-sandbox" 2>/dev/null || chmod +x "${DEST_DIR}/chrome-sandbox"
fi

log_ok "Application files successfully installed to ${DEST_DIR}"

# ------------------------------------------------------------------------------
# Icon Setup
# ------------------------------------------------------------------------------
log_info "Configuring application icon..."
ICON_PNG="${DEST_DIR}/antigravity.png"

if [[ -n "${CUSTOM_ICON}" ]]; then
    if [[ ! -f "${CUSTOM_ICON}" ]]; then
        log_error "Specified custom icon file not found: ${CUSTOM_ICON}"
        exit 1
    fi
    log_info "Using custom icon: ${CUSTOM_ICON}"
    cp "${CUSTOM_ICON}" "${ICON_PNG}"
else
    # Extract official 512x512 icon from resources/app.asar
    ASAR_PATH="${DEST_DIR}/resources/app.asar"
    if [[ -f "${ASAR_PATH}" ]]; then
        log_info "Extracting official 512x512 icon from resources/app.asar..."
        python3 - "${ASAR_PATH}" "${ICON_PNG}" << 'EOF'
import sys, struct, json, os

asar_path = sys.argv[1]
out_path = sys.argv[2]

try:
    with open(asar_path, "rb") as f:
        magic, header_len = struct.unpack("<II", f.read(8))
        f.seek(12)
        json_len = struct.unpack("<I", f.read(4))[0]
        header_json = f.read(json_len).decode("utf-8")
        header = json.loads(header_json)
        
        def find_icon(node):
            for k, v in node.get("files", {}).items():
                if "files" in v:
                    res = find_icon(v)
                    if res: return res
                elif k.lower() in ("icon.png", "antigravity.png", "app.png") or (k.lower().endswith(".png") and "icon" in k.lower()):
                    return v
            return None

        target = find_icon(header)
        if not target or "offset" not in target or "size" not in target:
            sys.exit(1)
            
        offset = int(target["offset"])
        size = int(target["size"])
        f.seek(8 + header_len + offset)
        data = f.read(size)
        
        if not data.startswith(b"\x89PNG\r\n\x1a\n"):
            sys.exit(1)
            
        with open(out_path, "wb") as out:
            out.write(data)
    sys.exit(0)
except Exception:
    sys.exit(1)
EOF
        if [[ $? -eq 0 && -s "${ICON_PNG}" ]]; then
            log_ok "Extracted official icon (512x512 PNG) to ${ICON_PNG}"
        else
            log_warn "Could not extract icon from app.asar."
        fi
    fi
fi

# Fallback: if icon still not generated, create a clean vector/canvas fallback
if [[ ! -s "${ICON_PNG}" ]]; then
    log_warn "Creating fallback icon..."
    python3 - "${ICON_PNG}" << 'EOF'
import sys
out_path = sys.argv[1]
try:
    from PIL import Image, ImageDraw
    img = Image.new('RGBA', (512, 512), color=(0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    # Circle background with Antigravity Blue / Indigo
    draw.ellipse([32, 32, 480, 480], fill=(66, 133, 244, 255))
    # Inner emblem
    draw.polygon([(256, 110), (390, 370), (122, 370)], fill=(255, 255, 255, 255))
    draw.polygon([(256, 190), (340, 350), (172, 350)], fill=(66, 133, 244, 255))
    img.save(out_path, format="PNG")
except Exception:
    pass
EOF
fi

# Install icons into FreeDesktop / KDE Plasma standard icon hierarchy
if [[ -s "${ICON_PNG}" ]]; then
    ICON_BASE="${HOME}/.local/share/icons/hicolor"
    mkdir -p "${ICON_BASE}/512x512/apps"
    cp -f "${ICON_PNG}" "${ICON_BASE}/512x512/apps/${DESKTOP_ID}.png"
    
    # Also generate common resolutions if PIL is available
    python3 - "${ICON_PNG}" "${ICON_BASE}" "${DESKTOP_ID}" << 'EOF'
import sys, os
from PIL import Image

src_icon = sys.argv[1]
icon_base = sys.argv[2]
app_id = sys.argv[3]

try:
    img = Image.open(src_icon)
    for dim in [256, 128, 64, 48, 32]:
        dest_dir = os.path.join(icon_base, f"{dim}x{dim}", "apps")
        os.makedirs(dest_dir, exist_ok=True)
        dest_file = os.path.join(dest_dir, f"{app_id}.png")
        resized = img.resize((dim, dim), Image.Resampling.LANCZOS)
        resized.save(dest_file, format="PNG")
except Exception:
    pass
EOF

    # Pixmap fallback
    mkdir -p "${HOME}/.local/share/pixmaps"
    cp -f "${ICON_PNG}" "${HOME}/.local/share/pixmaps/${DESKTOP_ID}.png"
    log_ok "Registered application icons in ~/.local/share/icons/hicolor"
fi

# ------------------------------------------------------------------------------
# Terminal Launcher Command
# ------------------------------------------------------------------------------
log_info "Configuring terminal command: ${BIN_DIR}/${DESKTOP_ID}"
mkdir -p "${BIN_DIR}"
LAUNCHER_SCRIPT="${BIN_DIR}/${DESKTOP_ID}"

cat > "${LAUNCHER_SCRIPT}" << EOF
#!/usr/bin/env bash
# Antigravity 2.0 CLI Launcher
# Launch the Antigravity desktop application from terminal

APP_EXEC="${DEST_DIR}/antigravity"

if [ ! -x "\$APP_EXEC" ]; then
    echo "Error: Antigravity executable not found at \$APP_EXEC" >&2
    exit 1
fi

exec "\$APP_EXEC" "\$@"
EOF

chmod +x "${LAUNCHER_SCRIPT}"
log_ok "Terminal launcher created: ${LAUNCHER_SCRIPT}"

# Verify PATH
if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
    log_warn "'${BIN_DIR}' is not currently in your PATH environment variable."
    log_warn "Add the following line to your ~/.bashrc or ~/.zshrc:"
    log_warn "  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ------------------------------------------------------------------------------
# Desktop Entry
# ------------------------------------------------------------------------------
log_info "Creating KDE Plasma desktop entry..."
APPLICATIONS_DIR="${HOME}/.local/share/applications"
mkdir -p "${APPLICATIONS_DIR}"
DESKTOP_FILE="${APPLICATIONS_DIR}/${DESKTOP_ID}.desktop"

cat > "${DESKTOP_FILE}" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=${APP_NAME}
GenericName=AI Development Platform
Comment=Antigravity 2.0 - Agentic Desktop Application
Exec=${DEST_DIR}/antigravity %U
Icon=${DESKTOP_ID}
Terminal=false
Categories=Development;IDE;
StartupWMClass=antigravity
MimeType=x-scheme-handler/antigravity;
Keywords=antigravity;agent;ai;coding;ide;gemini;
StartupNotify=true
EOF

chmod +x "${DESKTOP_FILE}"
log_ok "Desktop entry created: ${DESKTOP_FILE}"

# Refresh caches for KDE Plasma
refresh_system_caches

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------
NEW_VERSION="unknown"
if [[ -f "${DEST_DIR}/resources/app.asar" ]]; then
    NEW_VERSION="$(get_app_version "${DEST_DIR}/resources/app.asar")"
fi

echo ""
echo -e "${GREEN}${BOLD}═════════════════════════════════════════════════════════════════════${RESET}"
if [[ "${OLD_VERSION}" != "none" && "${OLD_VERSION}" != "unknown" ]]; then
    echo -e "${GREEN}${BOLD}   Antigravity 2.0 has been successfully updated! (v${OLD_VERSION} -> v${NEW_VERSION})${RESET}"
else
    echo -e "${GREEN}${BOLD}   Antigravity 2.0 (v${NEW_VERSION}) has been successfully installed!     ${RESET}"
fi
echo -e "${GREEN}${BOLD}═════════════════════════════════════════════════════════════════════${RESET}"
echo -e "  • ${BOLD}Version:${RESET}                ${NEW_VERSION}"
echo -e "  • ${BOLD}Application Directory:${RESET}  ${DEST_DIR}"
echo -e "  • ${BOLD}Terminal Command:${RESET}       ${BIN_DIR}/${DESKTOP_ID}  (run: '${DESKTOP_ID}')"
echo -e "  • ${BOLD}Desktop Entry:${RESET}          ${DESKTOP_FILE}"
echo -e "  • ${BOLD}Application Icon:${RESET}       ${ICON_PNG}"
echo ""
echo -e "You can launch Antigravity from:"
echo -e "  1. KDE Application Launcher / KRunner (press ${BOLD}Alt+Space${RESET} and type ${BOLD}Antigravity${RESET})"
echo -e "  2. Terminal by typing: ${BOLD}${DESKTOP_ID}${RESET}"
echo ""
