#!/usr/bin/env bash
# ==============================================================================
# install-godot.sh
# 
# Installer & In-Place Updater utility for Godot Engine on Fedora Linux
# (KDE Plasma & Freedesktop compliant).
# 
# Generated by: Antigravity AI Assistant (Google DeepMind)
# Model: Gemini 3.8 Flash
# Date: October 2026
# SPDX-License-Identifier: MIT
# License: MIT (see LICENSE)
# ==============================================================================

set -euo pipefail

# Text formatting
BOLD="\033[1m"
GREEN="\033[32m"
BLUE="\033[34m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

log_info()  { echo -e "${BLUE}${BOLD}[INFO]${RESET} $*"; }
log_ok()    { echo -e "${GREEN}${BOLD}[OK]${RESET} $*"; }
log_warn()  { echo -e "${YELLOW}${BOLD}[WARN]${RESET} $*"; }
log_error() { echo -e "${RED}${BOLD}[ERROR]${RESET} $*" >&2; }

# Defaults
# Note: Godot stores user project configurations, export templates, and shader
# caches in ~/.local/share/godot. We intentionally install the application files
# into ~/.local/share/godot-engine so user data is never disturbed during updates.
DEFAULT_DEST_DIR="${HOME}/.local/share/godot-engine"
DEFAULT_BIN_DIR="${HOME}/.local/bin"
APP_NAME="Godot Engine"
DESKTOP_ID="godot"

DEST_DIR="${DEFAULT_DEST_DIR}"
BIN_DIR="${DEFAULT_BIN_DIR}"
CUSTOM_ICON=""
ARCHIVE_PATH=""
DO_UNINSTALL=false

show_help() {
    echo -e "${BOLD}Godot Engine Installer & In-Place Updater for Fedora Linux (KDE Plasma)${RESET}

Usage:
  $(basename "$0") [OPTIONS] [PATH_TO_ZIP]

Options:
  -d, --dest <DIR>       Destination directory for application files
                         (default: ${DEFAULT_DEST_DIR})
  -b, --bin-dir <DIR>    Directory for the terminal launcher command
                         (default: ${DEFAULT_BIN_DIR})
  -i, --icon <PATH>      Custom application icon (.png or .svg).
                         If omitted, uses the active desktop icon theme (e.g. Tela)
                         via 'Icon=godot' with embedded fallback.
  -u, --uninstall        Remove Godot Engine installation, desktop entry,
                         and terminal launcher. User data and settings in
                         ~/.local/share/godot and ~/.config/godot remain intact.
  -h, --help             Show this help message and exit.

Examples:
  # Install using an explicit zip archive path:
  $(basename "$0") ~/Downloads/Godot_v4.7.2-stable_linux.x86_64.zip

  # Install using automatic detection from ~/Downloads or current dir:
  $(basename "$0")

  # Install with a custom icon:
  $(basename "$0") --icon ~/Pictures/my-godot-icon.png ~/Downloads/Godot.zip

  # Uninstall:
  $(basename "$0") --uninstall"
}

# Parse options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_help
            exit 0
            ;;
        -d|--dest)
            DEST_DIR="$(realpath -m "$2")"
            shift 2
            ;;
        -b|--bin-dir)
            BIN_DIR="$(realpath -m "$2")"
            shift 2
            ;;
        -i|--icon)
            CUSTOM_ICON="$(realpath "$2")"
            shift 2
            ;;
        -u|--uninstall)
            DO_UNINSTALL=true
            shift
            ;;
        -*)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            if [[ -z "${ARCHIVE_PATH}" ]]; then
                ARCHIVE_PATH="$(realpath "$1")"
            else
                log_error "Unexpected argument: $1"
                exit 1
            fi
            shift
            ;;
    esac
done

# ------------------------------------------------------------------------------
# Refresh desktop and icon databases
# ------------------------------------------------------------------------------
refresh_system_caches() {
    log_info "Updating system icon and desktop entry caches..."

    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true
    fi

    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "${HOME}/.local/share/applications" 2>/dev/null || true
    fi

    # KDE Plasma Sycoca cache refresh (Plasma 6 / Plasma 5)
    if command -v kbuildsycoca6 >/dev/null 2>&1; then
        kbuildsycoca6 2>/dev/null || true
    elif command -v kbuildsycoca5 >/dev/null 2>&1; then
        kbuildsycoca5 2>/dev/null || true
    fi
}

# ------------------------------------------------------------------------------
# Version detection helper
# ------------------------------------------------------------------------------
get_app_version() {
    local bin_path="$1"
    local archive_path="${2:-}"
    local ver=""

    if [[ -x "${bin_path}" ]]; then
        # Godot --version prints e.g.: 4.7.2.stable.official.ed1daf0bf
        ver="$("${bin_path}" --version 2>/dev/null | head -n 1 | tr -d '\r\n' || true)"
    fi

    if [[ -z "${ver}" && -n "${archive_path}" ]]; then
        local base
        base="$(basename "${archive_path}")"
        # Match Godot_v4.7.2-stable...
        if [[ "${base}" =~ [Gg]odot_v?([0-9]+(\.[0-9]+)*(-[a-zA-Z0-9._]+)?) ]]; then
            ver="${BASH_REMATCH[1]}"
        fi
    fi

    if [[ -z "${ver}" ]]; then
        ver="unknown"
    fi
    echo "${ver}"
}

# ------------------------------------------------------------------------------
# Uninstall Routine
# ------------------------------------------------------------------------------
if [[ "${DO_UNINSTALL}" == "true" ]]; then
    log_info "Starting uninstallation of Godot Engine..."

    # Remove application directory
    if [[ -d "${DEST_DIR}" ]]; then
        rm -rf "${DEST_DIR}"
        log_ok "Removed application directory: ${DEST_DIR}"
    fi

    # Remove terminal binary
    if [[ -f "${BIN_DIR}/${DESKTOP_ID}" || -L "${BIN_DIR}/${DESKTOP_ID}" ]]; then
        rm -f "${BIN_DIR}/${DESKTOP_ID}"
        log_ok "Removed terminal launcher: ${BIN_DIR}/${DESKTOP_ID}"
    fi

    # Remove desktop entry
    DESKTOP_FILE="${HOME}/.local/share/applications/${DESKTOP_ID}.desktop"
    if [[ -f "${DESKTOP_FILE}" ]]; then
        rm -f "${DESKTOP_FILE}"
        log_ok "Removed desktop entry: ${DESKTOP_FILE}"
    fi

    # Remove any custom or fallback icons installed into hicolor
    ICON_BASE="${HOME}/.local/share/icons/hicolor"
    for size in 16x16 24x24 32x32 48x48 64x64 128x128 256x256 512x512 scalable; do
        for ext in png svg; do
            target="${ICON_BASE}/${size}/apps/${DESKTOP_ID}.${ext}"
            if [[ -f "${target}" || -L "${target}" ]]; then
                rm -f "${target}"
            fi
        done
    done
    rm -f "${HOME}/.local/share/pixmaps/${DESKTOP_ID}.png" 2>/dev/null || true
    rm -f "${HOME}/.local/share/pixmaps/${DESKTOP_ID}.svg" 2>/dev/null || true

    refresh_system_caches

    log_info "Note: User projects, export templates, and settings in ~/.local/share/godot and ~/.config/godot were kept safe and untouched."
    log_ok "Godot Engine uninstalled successfully."
    exit 0
fi

# ------------------------------------------------------------------------------
# Archive resolution
# ------------------------------------------------------------------------------
if [[ -z "${ARCHIVE_PATH}" ]]; then
    log_info "No zip archive path provided. Checking current directory and ~/Downloads..."
    # Find archives and sort by modification timestamp (newest first)
    NEWEST_ARCHIVE="$(find . "${HOME}/Downloads" -maxdepth 1 \( -iname "*godot*.zip" \) -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n 1 | cut -d' ' -f2-)"

    if [[ -n "${NEWEST_ARCHIVE}" && -f "${NEWEST_ARCHIVE}" ]]; then
        ARCHIVE_PATH="${NEWEST_ARCHIVE}"
        log_info "Auto-detected most recently downloaded build: ${ARCHIVE_PATH}"
    else
        log_error "Could not find a Godot .zip archive in current directory or ~/Downloads."
        log_error "Please specify the path: $(basename "$0") /path/to/Godot_vx.x_linux.zip"
        exit 1
    fi
fi

if [[ ! -f "${ARCHIVE_PATH}" ]]; then
    log_error "Archive file not found: ${ARCHIVE_PATH}"
    exit 1
fi

# Verify it is a valid zip archive
if ! unzip -tq "${ARCHIVE_PATH}" >/dev/null 2>&1; then
    log_error "The specified file is not a valid zip archive: ${ARCHIVE_PATH}"
    exit 1
fi

# Check required system utilities
for tool in unzip file; do
    if ! command -v "${tool}" >/dev/null 2>&1; then
        log_error "Required utility '${tool}' is not installed."
        exit 1
    fi
done

# Check if application is currently running
if pgrep -fi "godot" >/dev/null 2>&1; then
    log_warn "Godot appears to be currently running."
    log_warn "If you experience issues, please close Godot before updating."
fi

# Detect currently installed version if updating
OLD_VERSION="none"
if [[ -x "${DEST_DIR}/godot" ]]; then
    OLD_VERSION="$(get_app_version "${DEST_DIR}/godot" "")"
fi

# ------------------------------------------------------------------------------
# Extraction to destination directory
# ------------------------------------------------------------------------------
log_info "Preparing installation destination: ${DEST_DIR}"
TEMP_EXTRACT_DIR="$(mktemp -d -t godot-install-XXXXXX)"

cleanup() {
    rm -rf "${TEMP_EXTRACT_DIR}"
}
trap cleanup EXIT

log_info "Extracting archive: ${ARCHIVE_PATH}..."
unzip -q "${ARCHIVE_PATH}" -d "${TEMP_EXTRACT_DIR}"

# Determine if archive extracted into a single root folder (e.g. Godot_v4.x_mono_linux_x86_64)
EXTRACTED_ITEMS=("${TEMP_EXTRACT_DIR}"/*)
SOURCE_ROOT="${TEMP_EXTRACT_DIR}"

if [[ ${#EXTRACTED_ITEMS[@]} -eq 1 && -d "${EXTRACTED_ITEMS[0]}" ]]; then
    SOURCE_ROOT="${EXTRACTED_ITEMS[0]}"
fi

# Locate the Godot executable binary
GODOT_BIN=""
while IFS= read -r cand; do
    if [[ -f "${cand}" ]]; then
        base="$(basename "${cand}")"
        if [[ "${base}" =~ ^[Gg]odot ]] && ( [[ -x "${cand}" ]] || file "${cand}" | grep -q "ELF" ); then
            GODOT_BIN="${cand}"
            break
        fi
    fi
done < <(find "${SOURCE_ROOT}" -maxdepth 2 -type f 2>/dev/null)

if [[ -z "${GODOT_BIN}" ]]; then
    # Broader fallback search for any ELF executable
    while IFS= read -r cand; do
        if [[ -f "${cand}" ]] && file "${cand}" | grep -q "ELF.*executable"; then
            GODOT_BIN="${cand}"
            break
        fi
    done < <(find "${SOURCE_ROOT}" -maxdepth 2 -type f 2>/dev/null)
fi

if [[ -z "${GODOT_BIN}" ]]; then
    log_error "Could not find a valid Godot executable inside the extracted archive."
    exit 1
fi

BIN_FILENAME="$(basename "${GODOT_BIN}")"
log_info "Identified Godot binary: ${BIN_FILENAME}"

# Install / replace target directory
mkdir -p "$(dirname "${DEST_DIR}")"
if [[ -d "${DEST_DIR}" ]]; then
    log_info "Replacing existing directory at ${DEST_DIR}..."
    rm -rf "${DEST_DIR}"
fi

mkdir -p "${DEST_DIR}"
cp -a "${SOURCE_ROOT}/." "${DEST_DIR}/"
chmod +x "${DEST_DIR}/${BIN_FILENAME}"

# Create a stable symlink inside DEST_DIR so godot can always be invoked via DEST_DIR/godot
ln -sfn "${BIN_FILENAME}" "${DEST_DIR}/godot"

log_ok "Application files successfully installed to ${DEST_DIR}"

# ------------------------------------------------------------------------------
# Icon Setup
# ------------------------------------------------------------------------------
log_info "Configuring application icon..."
ICON_NAME="${DESKTOP_ID}"
ICON_INFO=""

if [[ -n "${CUSTOM_ICON}" ]]; then
    if [[ ! -f "${CUSTOM_ICON}" ]]; then
        log_error "Specified custom icon file not found: ${CUSTOM_ICON}"
        exit 1
    fi
    log_info "Installing custom icon: ${CUSTOM_ICON}"
    ICON_BASE="${HOME}/.local/share/icons/hicolor"
    if [[ "${CUSTOM_ICON}" == *.svg ]]; then
        mkdir -p "${ICON_BASE}/scalable/apps"
        cp -f "${CUSTOM_ICON}" "${ICON_BASE}/scalable/apps/${DESKTOP_ID}.svg"
    else
        mkdir -p "${ICON_BASE}/512x512/apps"
        cp -f "${CUSTOM_ICON}" "${ICON_BASE}/512x512/apps/${DESKTOP_ID}.png"
    fi
    ICON_INFO="custom (${CUSTOM_ICON})"
    log_ok "Custom icon registered"
else
    # Check if the active icon theme or system already provides a 'godot' icon
    # (e.g. Tela-circle, Breeze, or standard freedesktop themes)
    THEME_ICON_FOUND="$(find "${HOME}/.local/share/icons" "/usr/share/icons" -maxdepth 5 -type f \( -path "*/scalable/apps/godot.svg" -o -path "*/apps/godot.svg" -o -path "*/scalable/apps/org.godotengine.Godot.svg" \) 2>/dev/null | head -n 1 || true)"

    if [[ -n "${THEME_ICON_FOUND}" ]]; then
        log_ok "Active/system icon theme provides '${ICON_NAME}' icon (${THEME_ICON_FOUND})"
        log_ok "Configured 'Icon=${ICON_NAME}' in desktop entry without file duplication"
        ICON_INFO="${ICON_NAME} (from active theme: $(basename "$(dirname "$(dirname "$(dirname "${THEME_ICON_FOUND}")")")"))"
    else
        # Safety fallback: only if the system has no godot icon in any theme
        log_warn "No 'godot' icon detected in installed icon themes; creating fallback SVG..."
        FALLBACK_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
        mkdir -p "${FALLBACK_DIR}"
        cat > "${FALLBACK_DIR}/${DESKTOP_ID}.svg" << 'EOF'
<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><rect width="54" height="54" x="5" y="5" fill="#f0f0f0" ry="27"/><g stroke-width=".75"><path fill="#47a5bf" d="m27.929 13.98-4.831 1.628.763 4.883-4.17 2.288-2.34-2.289-4.884 4.883 3.255 3.255v8.85l.815.053v2.645l3.255 1.27V38.65c2.417.524 3.506.752 4.883.863v2.544l3.255.968v-3.002h8.14v3.002l3.255-.968v-2.544c1.377-.11 2.466-.337 4.883-.863v2.796l3.255-1.27V37.53l.815-.052v-8.851l3.255-3.255-4.883-4.883-2.342 2.29-4.17-2.29.763-4.883-4.835-1.627-1.83 3.254h-4.475L27.93 13.98zm-4.881 14.65a4.07 4.07 0 1 1 0 8.138 4.07 4.07 0 0 1 0-8.14zm17.904 0a4.07 4.07 0 1 1 0 8.138 4.07 4.07 0 0 1 0-8.14zM32 31.88a1.624 1.624 0 0 1 1.626 1.629v3.255c0 .902-.724 1.628-1.626 1.628a1.625 1.625 0 0 1-1.629-1.628V33.51c0-.901.727-1.629 1.629-1.629zm-19.024 5.7.053 3.255c3.933 6.008 9.864 9.54 18.972 9.156 9.114.385 15.04-3.148 18.971-9.156l.052-3.255-2.747.863v2.393c-.796.512-3.256 1.184-4.883 1.628v-2.647l-3.257.51v2.137c-.922.777-2.639 1.291-4.884 1.628v-3.255h-6.509v3.255c-2.245-.337-3.961-.85-4.883-1.628v-2.137l-3.257-.51v2.647c-1.628-.444-4.087-1.116-4.883-1.629v-2.392z"/><path fill="#4d4d4d" d="M25.49 32.698a2.442 2.442 0 1 1-4.884 0 2.442 2.442 0 1 1 4.883 0zm17.904 0a2.442 2.442 0 1 1-4.883 0 2.442 2.442 0 1 1 4.883 0"/></g></svg>
EOF
        ICON_INFO="${ICON_NAME} (fallback SVG installed)"
    fi
fi

# ------------------------------------------------------------------------------
# Terminal Launcher Command
# ------------------------------------------------------------------------------
log_info "Configuring terminal command: ${BIN_DIR}/${DESKTOP_ID}"
mkdir -p "${BIN_DIR}"
LAUNCHER_SCRIPT="${BIN_DIR}/${DESKTOP_ID}"

cat > "${LAUNCHER_SCRIPT}" << EOF
#!/usr/bin/env bash
# Godot Engine CLI Launcher
# Launch the Godot Engine desktop application / editor from terminal

APP_EXEC="${DEST_DIR}/godot"

if [ ! -x "\$APP_EXEC" ]; then
    echo "Error: Godot executable not found at \$APP_EXEC" >&2
    exit 1
fi

exec "\$APP_EXEC" "\$@"
EOF

chmod +x "${LAUNCHER_SCRIPT}"
log_ok "Terminal launcher created: ${LAUNCHER_SCRIPT}"

# Verify PATH
if [[ ":$PATH:" != *":${BIN_DIR}:"* ]]; then
    log_warn "'${BIN_DIR}' is not currently in your PATH environment variable."
    log_warn "Add the following line to your ~/.bashrc or ~/.zshrc:"
    log_warn "  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ------------------------------------------------------------------------------
# Desktop Entry
# ------------------------------------------------------------------------------
log_info "Creating KDE Plasma desktop entry..."
APPLICATIONS_DIR="${HOME}/.local/share/applications"
mkdir -p "${APPLICATIONS_DIR}"
DESKTOP_FILE="${APPLICATIONS_DIR}/${DESKTOP_ID}.desktop"

cat > "${DESKTOP_FILE}" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=${APP_NAME}
GenericName=Libre Game Engine
Comment=Multi-platform 2D and 3D game engine with a feature-rich editor
Exec=${DEST_DIR}/godot %F
Icon=${DESKTOP_ID}
Terminal=false
Categories=Development;IDE;
MimeType=application/x-godot-project;
StartupWMClass=Godot
Keywords=godot;game;engine;gamedev;2d;3d;
StartupNotify=true
EOF

chmod +x "${DESKTOP_FILE}"
log_ok "Desktop entry created: ${DESKTOP_FILE}"

# Refresh caches for KDE Plasma
refresh_system_caches

# ------------------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------------------
NEW_VERSION="unknown"
if [[ -x "${DEST_DIR}/godot" ]]; then
    NEW_VERSION="$(get_app_version "${DEST_DIR}/godot" "${ARCHIVE_PATH}")"
fi

echo ""
echo -e "${GREEN}${BOLD}═════════════════════════════════════════════════════════════════════${RESET}"
if [[ "${OLD_VERSION}" != "none" && "${OLD_VERSION}" != "unknown" ]]; then
    echo -e "${GREEN}${BOLD}   Godot Engine has been successfully updated! (v${OLD_VERSION} -> v${NEW_VERSION})${RESET}"
else
    echo -e "${GREEN}${BOLD}   Godot Engine (v${NEW_VERSION}) has been successfully installed!     ${RESET}"
fi
echo -e "${GREEN}${BOLD}═════════════════════════════════════════════════════════════════════${RESET}"
echo -e "  • ${BOLD}Version:${RESET}                ${NEW_VERSION}"
echo -e "  • ${BOLD}Application Directory:${RESET}  ${DEST_DIR}"
echo -e "  • ${BOLD}Terminal Command:${RESET}       ${BIN_DIR}/${DESKTOP_ID}  (run: '${DESKTOP_ID}')"
echo -e "  • ${BOLD}Desktop Entry:${RESET}          ${DESKTOP_FILE}"
echo -e "  • ${BOLD}Application Icon:${RESET}       ${ICON_INFO}"
echo ""
echo -e "You can launch Godot Engine from:"
echo -e "  1. KDE Application Launcher / KRunner (press ${BOLD}Alt+Space${RESET} and type ${BOLD}Godot${RESET})"
echo -e "  2. Terminal by typing: ${BOLD}${DESKTOP_ID}${RESET}"
echo ""
